//////////////////////////////////////////////////////////////////////
//
// TaRunlist.C
//   Bryan Moffit - July 2005
//
//   Multirun class to take care of the runlist generated by 
//     the MySQL database.  
//    For now, uses the output from a perl script.  Later on, may
//    be adapted to obtain data directly from the database (if
//    ROOT is compiled with the libMysql).
//
//////////////////////////////////////////////////////////////////////

#include "multirun/TaRunlist.h"
#include <fstream>
#include <iostream>
#include "TString.h"

TaRunlist::TaRunlist():
  isLoaded(kFALSE),
  mapRunlist()
{
  perl_filename = "runlist.txt";
  isLoaded = Load();
}

TaRunlist::TaRunlist(TString filename):
  isLoaded(kFALSE),
  perl_filename(),
  mapRunlist()
{
  perl_filename = filename;
  isLoaded = Load();
}

Bool_t TaRunlist::Load() 
{
  ifstream ifile(perl_filename);
  if(!ifile.good()) {
    cerr << "TaRunlist: Unable to Load " << perl_filename << endl;
    return kFALSE;
  }
  
  while(ifile.good()) {
    Run thisrun;
    ifile >> thisrun.runnumber >> thisrun.slug >> thisrun.slowsign;
    ifile >> thisrun.LeftDetLo >> thisrun.LeftDetHi;
    ifile >> thisrun.RightDetLo >> thisrun.RightDetHi;
    mapRunlist[thisrun.runnumber] = thisrun;
  }
  return kTRUE;
}

vector <Int_t> TaRunlist::GetListOfRuns(Int_t slug) 
{
  // Get a list of runs from a certain slug.

  vector <Int_t> vRuns(0);

  if(!isLoaded) return vRuns;

  Run thisrun;
  map<Int_t, Run>::iterator i;
  for(i = mapRunlist.begin(); 
      i!=mapRunlist.end(); i++) 
    {
      thisrun = i->second;
      if(thisrun.slug==slug) vRuns.push_back(thisrun.runnumber);
    }

  return vRuns;
}

vector <Int_t> TaRunlist::GetListOfRuns() 
{
  // Get a list of all runs

  vector <Int_t> vRuns(0);

  if(!isLoaded) return vRuns;

  Run thisrun;
  map<Int_t, Run>::iterator i;
  for(i = mapRunlist.begin(); 
      i!=mapRunlist.end(); i++) 
    {
      thisrun = i->second;
      vRuns.push_back(thisrun.runnumber);
    }

  return vRuns;
}
