//////////////////////////////////////////////////////////////////////////
//
//  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE 
//  Note: This header file is generated by the script genDevTypes.pl .
//  Do not edit it; make changes to the script instead.
//  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE 
//
//////////////////////////////////////////////////////////////////////////
//
//     HALL A C++/ROOT Parity Analyzer  Pan           
//
//           DevTypes.hh  (definition file)
//           ^^^^^^^^^^^
//
//    Authors :  R. Holmes, A. Vacheret, R. Michaels
//
//  Defines arbitrary integer "keys" used to access data (both raw 
//  and calibrated) from fData array in TaEvent class.   
//  The keys have easy-to-remember names.  
//  Restrictions: 
//    1. the keys must be unique.
//    2. MAXKEYS must be > largest key.
//    3. ordering of keys affects TaEvent::Decode().
//
//////////////////////////////////////////////////////////////////////////
 
#define   MAXKEYS        707
#define   ADCREADOUT     1
#define   SCALREADOUT    2
#define   SCALREADOUT    2
#define   TBDREADOUT     3
#define   TIRREADOUT     4

// Keys for getting data from devices.
// They keys are mapped to devices automatically.
// Use these keys for  TaEvent::GetData(Int_t key)

// Stripline BPMs

#define   STROFF     1     // Stripline BPMs start here
#define   STRNUM     12     // number of striplines defined below

// XP, XM, YP, YM = antennas; X, Y = calibrated position;
// XWS, YWS, WS = X, Y, and total wiresum

// Hall A striplines
#define   IBPM8XP    1
#define   IBPM8XM    2
#define   IBPM8YP    3
#define   IBPM8YM    4
#define   IBPM8X     5
#define   IBPM8Y     6
#define   IBPM8XWS   7
#define   IBPM8YWS   8
#define   IBPM8WS    9

#define   IBPM10XP    10
#define   IBPM10XM    11
#define   IBPM10YP    12
#define   IBPM10YM    13
#define   IBPM10X     14
#define   IBPM10Y     15
#define   IBPM10XWS   16
#define   IBPM10YWS   17
#define   IBPM10WS    18

#define   IBPM12XP    19
#define   IBPM12XM    20
#define   IBPM12YP    21
#define   IBPM12YM    22
#define   IBPM12X     23
#define   IBPM12Y     24
#define   IBPM12XWS   25
#define   IBPM12YWS   26
#define   IBPM12WS    27

#define   IBPM4AXP    28
#define   IBPM4AXM    29
#define   IBPM4AYP    30
#define   IBPM4AYM    31
#define   IBPM4AX     32
#define   IBPM4AY     33
#define   IBPM4AXWS   34
#define   IBPM4AYWS   35
#define   IBPM4AWS    36

#define   IBPM4BXP    37
#define   IBPM4BXM    38
#define   IBPM4BYP    39
#define   IBPM4BYM    40
#define   IBPM4BX     41
#define   IBPM4BY     42
#define   IBPM4BXWS   43
#define   IBPM4BYWS   44
#define   IBPM4BWS    45

// Injector striplines
#define   IBPM1I02XP    46
#define   IBPM1I02XM    47
#define   IBPM1I02YP    48
#define   IBPM1I02YM    49
#define   IBPM1I02X     50
#define   IBPM1I02Y     51
#define   IBPM1I02XWS   52
#define   IBPM1I02YWS   53
#define   IBPM1I02WS    54

#define   IBPM1I04XP    55
#define   IBPM1I04XM    56
#define   IBPM1I04YP    57
#define   IBPM1I04YM    58
#define   IBPM1I04X     59
#define   IBPM1I04Y     60
#define   IBPM1I04XWS   61
#define   IBPM1I04YWS   62
#define   IBPM1I04WS    63

#define   IBPM1I06XP    64
#define   IBPM1I06XM    65
#define   IBPM1I06YP    66
#define   IBPM1I06YM    67
#define   IBPM1I06X     68
#define   IBPM1I06Y     69
#define   IBPM1I06XWS   70
#define   IBPM1I06YWS   71
#define   IBPM1I06WS    72

#define   IBPM0I02XP    73
#define   IBPM0I02XM    74
#define   IBPM0I02YP    75
#define   IBPM0I02YM    76
#define   IBPM0I02X     77
#define   IBPM0I02Y     78
#define   IBPM0I02XWS   79
#define   IBPM0I02YWS   80
#define   IBPM0I02WS    81

#define   IBPM0I02AXP    82
#define   IBPM0I02AXM    83
#define   IBPM0I02AYP    84
#define   IBPM0I02AYM    85
#define   IBPM0I02AX     86
#define   IBPM0I02AY     87
#define   IBPM0I02AXWS   88
#define   IBPM0I02AYWS   89
#define   IBPM0I02AWS    90

#define   IBPM0L02XP    91
#define   IBPM0L02XM    92
#define   IBPM0L02YP    93
#define   IBPM0L02YM    94
#define   IBPM0L02X     95
#define   IBPM0L02Y     96
#define   IBPM0L02XWS   97
#define   IBPM0L02YWS   98
#define   IBPM0L02WS    99

#define   IBPM0L06XP    100
#define   IBPM0L06XM    101
#define   IBPM0L06YP    102
#define   IBPM0L06YM    103
#define   IBPM0L06X     104
#define   IBPM0L06Y     105
#define   IBPM0L06XWS   106
#define   IBPM0L06YWS   107
#define   IBPM0L06WS    108


// Cavity BPMs
#define   CAVOFF     109     // Cavity BPMs start here
#define   CAVNUM     4     // number of cavities defined below

// XR, YR = raw data; X, Y = calibrated position

#define   IBPMCAV1XR    109
#define   IBPMCAV1YR    110
#define   IBPMCAV1X     111
#define   IBPMCAV1Y     112

#define   IBPMCAV2XR    113
#define   IBPMCAV2YR    114
#define   IBPMCAV2X     115
#define   IBPMCAV2Y     116

#define   IBPMCAV3XR    117
#define   IBPMCAV3YR    118
#define   IBPMCAV3X     119
#define   IBPMCAV3Y     120

#define   IBPMCAV4XR    121
#define   IBPMCAV4YR    122
#define   IBPMCAV4X     123
#define   IBPMCAV4Y     124


// Old (HAPPEX-I era) BCMs

#define   BCMOFF     125     // Old BCMs start here
#define   BCMNUM     4     // number of old BCMs defined below

// R = raw data; "" = calibrated data

#define   IBCM1R     125
#define   IBCM1      126

#define   IBCM2R     127
#define   IBCM2      128

#define   IBCM3R     129
#define   IBCM3      130

#define   IBCM4R     131
#define   IBCM4      132


// G0 BCMs

#define   CCMOFF     133     // G0 BCMs start here
#define   CCMNUM     4     // number of G0 BCMs defined below

// R = raw data; "" = calibrated data

#define   IBCMCAV1R     133
#define   IBCMCAV1      134

#define   IBCMCAV2R     135
#define   IBCMCAV2      136

#define   IBCMCAV3R     137
#define   IBCMCAV3      138

#define   IBCMCAV4R     139
#define   IBCMCAV4      140


// Batteries

#define   BATOFF     141     // Batteries start here
#define   BATNUM     5     // number of batteries defined below

#define   IBATT1      141
#define   IBATT2      142
#define   IBATT3      143
#define   IBATT4      144
#define   IBATT5      145

// Detectors

#define   DETOFF     146     // Detectorss start here
#define   DETNUM     4     // number of detectors defined below

// R = raw data; "" = calibrated data

#define   IDET1R     146
#define   IDET1      147

#define   IDET2R     148
#define   IDET2      149

#define   IDET3R     150
#define   IDET3      151

#define   IDET4R     152
#define   IDET4      153


// ADC data.  Data are arranged in sequence starting with ADC0_0
// First index is the adc#, second is channel#.  Indices start at 0
// ADC# 0 - 9 are in first crate, 10 in next crate, etc.  

// First the raw data

#define   ADCOFF     154     // Raw ADCs start here
#define   ADCNUM     23     // number of ADCs defined below

#define   IADC0_0     154
#define   IADC0_1     155
#define   IADC0_2     156
#define   IADC0_3     157
#define   IADC1_0     158
#define   IADC1_1     159
#define   IADC1_2     160
#define   IADC1_3     161
#define   IADC2_0     162
#define   IADC2_1     163
#define   IADC2_2     164
#define   IADC2_3     165
#define   IADC3_0     166
#define   IADC3_1     167
#define   IADC3_2     168
#define   IADC3_3     169
#define   IADC4_0     170
#define   IADC4_1     171
#define   IADC4_2     172
#define   IADC4_3     173
#define   IADC5_0     174
#define   IADC5_1     175
#define   IADC5_2     176
#define   IADC5_3     177
#define   IADC6_0     178
#define   IADC6_1     179
#define   IADC6_2     180
#define   IADC6_3     181
#define   IADC7_0     182
#define   IADC7_1     183
#define   IADC7_2     184
#define   IADC7_3     185
#define   IADC8_0     186
#define   IADC8_1     187
#define   IADC8_2     188
#define   IADC8_3     189
#define   IADC9_0     190
#define   IADC9_1     191
#define   IADC9_2     192
#define   IADC9_3     193
#define   IADC10_0     194
#define   IADC10_1     195
#define   IADC10_2     196
#define   IADC10_3     197
#define   IADC11_0     198
#define   IADC11_1     199
#define   IADC11_2     200
#define   IADC11_3     201
#define   IADC12_0     202
#define   IADC12_1     203
#define   IADC12_2     204
#define   IADC12_3     205
#define   IADC13_0     206
#define   IADC13_1     207
#define   IADC13_2     208
#define   IADC13_3     209
#define   IADC14_0     210
#define   IADC14_1     211
#define   IADC14_2     212
#define   IADC14_3     213
#define   IADC15_0     214
#define   IADC15_1     215
#define   IADC15_2     216
#define   IADC15_3     217
#define   IADC16_0     218
#define   IADC16_1     219
#define   IADC16_2     220
#define   IADC16_3     221
#define   IADC17_0     222
#define   IADC17_1     223
#define   IADC17_2     224
#define   IADC17_3     225
#define   IADC18_0     226
#define   IADC18_1     227
#define   IADC18_2     228
#define   IADC18_3     229
#define   IADC19_0     230
#define   IADC19_1     231
#define   IADC19_2     232
#define   IADC19_3     233
#define   IADC20_0     234
#define   IADC20_1     235
#define   IADC20_2     236
#define   IADC20_3     237
#define   IADC21_0     238
#define   IADC21_1     239
#define   IADC21_2     240
#define   IADC21_3     241
#define   IADC22_0     242
#define   IADC22_1     243
#define   IADC22_2     244
#define   IADC22_3     245

// Now the calibrated data

#define   ACCOFF     246     // Calibrated ADCs start here

#define   IADC0_0_CAL     246
#define   IADC0_1_CAL     247
#define   IADC0_2_CAL     248
#define   IADC0_3_CAL     249
#define   IADC1_0_CAL     250
#define   IADC1_1_CAL     251
#define   IADC1_2_CAL     252
#define   IADC1_3_CAL     253
#define   IADC2_0_CAL     254
#define   IADC2_1_CAL     255
#define   IADC2_2_CAL     256
#define   IADC2_3_CAL     257
#define   IADC3_0_CAL     258
#define   IADC3_1_CAL     259
#define   IADC3_2_CAL     260
#define   IADC3_3_CAL     261
#define   IADC4_0_CAL     262
#define   IADC4_1_CAL     263
#define   IADC4_2_CAL     264
#define   IADC4_3_CAL     265
#define   IADC5_0_CAL     266
#define   IADC5_1_CAL     267
#define   IADC5_2_CAL     268
#define   IADC5_3_CAL     269
#define   IADC6_0_CAL     270
#define   IADC6_1_CAL     271
#define   IADC6_2_CAL     272
#define   IADC6_3_CAL     273
#define   IADC7_0_CAL     274
#define   IADC7_1_CAL     275
#define   IADC7_2_CAL     276
#define   IADC7_3_CAL     277
#define   IADC8_0_CAL     278
#define   IADC8_1_CAL     279
#define   IADC8_2_CAL     280
#define   IADC8_3_CAL     281
#define   IADC9_0_CAL     282
#define   IADC9_1_CAL     283
#define   IADC9_2_CAL     284
#define   IADC9_3_CAL     285
#define   IADC10_0_CAL     286
#define   IADC10_1_CAL     287
#define   IADC10_2_CAL     288
#define   IADC10_3_CAL     289
#define   IADC11_0_CAL     290
#define   IADC11_1_CAL     291
#define   IADC11_2_CAL     292
#define   IADC11_3_CAL     293
#define   IADC12_0_CAL     294
#define   IADC12_1_CAL     295
#define   IADC12_2_CAL     296
#define   IADC12_3_CAL     297
#define   IADC13_0_CAL     298
#define   IADC13_1_CAL     299
#define   IADC13_2_CAL     300
#define   IADC13_3_CAL     301
#define   IADC14_0_CAL     302
#define   IADC14_1_CAL     303
#define   IADC14_2_CAL     304
#define   IADC14_3_CAL     305
#define   IADC15_0_CAL     306
#define   IADC15_1_CAL     307
#define   IADC15_2_CAL     308
#define   IADC15_3_CAL     309
#define   IADC16_0_CAL     310
#define   IADC16_1_CAL     311
#define   IADC16_2_CAL     312
#define   IADC16_3_CAL     313
#define   IADC17_0_CAL     314
#define   IADC17_1_CAL     315
#define   IADC17_2_CAL     316
#define   IADC17_3_CAL     317
#define   IADC18_0_CAL     318
#define   IADC18_1_CAL     319
#define   IADC18_2_CAL     320
#define   IADC18_3_CAL     321
#define   IADC19_0_CAL     322
#define   IADC19_1_CAL     323
#define   IADC19_2_CAL     324
#define   IADC19_3_CAL     325
#define   IADC20_0_CAL     326
#define   IADC20_1_CAL     327
#define   IADC20_2_CAL     328
#define   IADC20_3_CAL     329
#define   IADC21_0_CAL     330
#define   IADC21_1_CAL     331
#define   IADC21_2_CAL     332
#define   IADC21_3_CAL     333
#define   IADC22_0_CAL     334
#define   IADC22_1_CAL     335
#define   IADC22_2_CAL     336
#define   IADC22_3_CAL     337

// DAC noise.

#define   DACOFF     338     // DACs start here
#define   DACNUM     23     // number of DACs defined below

#define   IDAC0      338
#define   IDAC1      339
#define   IDAC2      340
#define   IDAC3      341
#define   IDAC4      342
#define   IDAC5      343
#define   IDAC6      344
#define   IDAC7      345
#define   IDAC8      346
#define   IDAC9      347
#define   IDAC10      348
#define   IDAC11      349
#define   IDAC12      350
#define   IDAC13      351
#define   IDAC14      352
#define   IDAC15      353
#define   IDAC16      354
#define   IDAC17      355
#define   IDAC18      356
#define   IDAC19      357
#define   IDAC20      358
#define   IDAC21      359
#define   IDAC22      360

// CSRs

#define   CSROFF     361     // CSRs start here
#define   CSRNUM     23     // number of CSRs defined below

#define   ICSR0      361
#define   ICSR1      362
#define   ICSR2      363
#define   ICSR3      364
#define   ICSR4      365
#define   ICSR5      366
#define   ICSR6      367
#define   ICSR7      368
#define   ICSR8      369
#define   ICSR9      370
#define   ICSR10      371
#define   ICSR11      372
#define   ICSR12      373
#define   ICSR13      374
#define   ICSR14      375
#define   ICSR15      376
#define   ICSR16      377
#define   ICSR17      378
#define   ICSR18      379
#define   ICSR19      380
#define   ICSR20      381
#define   ICSR21      382
#define   ICSR22      383

// Raw scalers

#define   SCAOFF     384     // Raw SCALERs start here
#define   SCANUM     4     // number of SCALERs defined below

#define   ISCALER0_0     384
#define   ISCALER0_1     385
#define   ISCALER0_2     386
#define   ISCALER0_3     387
#define   ISCALER0_4     388
#define   ISCALER0_5     389
#define   ISCALER0_6     390
#define   ISCALER0_7     391
#define   ISCALER0_8     392
#define   ISCALER0_9     393
#define   ISCALER0_10     394
#define   ISCALER0_11     395
#define   ISCALER0_12     396
#define   ISCALER0_13     397
#define   ISCALER0_14     398
#define   ISCALER0_15     399
#define   ISCALER0_16     400
#define   ISCALER0_17     401
#define   ISCALER0_18     402
#define   ISCALER0_19     403
#define   ISCALER0_20     404
#define   ISCALER0_21     405
#define   ISCALER0_22     406
#define   ISCALER0_23     407
#define   ISCALER0_24     408
#define   ISCALER0_25     409
#define   ISCALER0_26     410
#define   ISCALER0_27     411
#define   ISCALER0_28     412
#define   ISCALER0_29     413
#define   ISCALER0_30     414
#define   ISCALER0_31     415

#define   ISCALER1_0     416
#define   ISCALER1_1     417
#define   ISCALER1_2     418
#define   ISCALER1_3     419
#define   ISCALER1_4     420
#define   ISCALER1_5     421
#define   ISCALER1_6     422
#define   ISCALER1_7     423
#define   ISCALER1_8     424
#define   ISCALER1_9     425
#define   ISCALER1_10     426
#define   ISCALER1_11     427
#define   ISCALER1_12     428
#define   ISCALER1_13     429
#define   ISCALER1_14     430
#define   ISCALER1_15     431
#define   ISCALER1_16     432
#define   ISCALER1_17     433
#define   ISCALER1_18     434
#define   ISCALER1_19     435
#define   ISCALER1_20     436
#define   ISCALER1_21     437
#define   ISCALER1_22     438
#define   ISCALER1_23     439
#define   ISCALER1_24     440
#define   ISCALER1_25     441
#define   ISCALER1_26     442
#define   ISCALER1_27     443
#define   ISCALER1_28     444
#define   ISCALER1_29     445
#define   ISCALER1_30     446
#define   ISCALER1_31     447

#define   ISCALER2_0     448
#define   ISCALER2_1     449
#define   ISCALER2_2     450
#define   ISCALER2_3     451
#define   ISCALER2_4     452
#define   ISCALER2_5     453
#define   ISCALER2_6     454
#define   ISCALER2_7     455
#define   ISCALER2_8     456
#define   ISCALER2_9     457
#define   ISCALER2_10     458
#define   ISCALER2_11     459
#define   ISCALER2_12     460
#define   ISCALER2_13     461
#define   ISCALER2_14     462
#define   ISCALER2_15     463
#define   ISCALER2_16     464
#define   ISCALER2_17     465
#define   ISCALER2_18     466
#define   ISCALER2_19     467
#define   ISCALER2_20     468
#define   ISCALER2_21     469
#define   ISCALER2_22     470
#define   ISCALER2_23     471
#define   ISCALER2_24     472
#define   ISCALER2_25     473
#define   ISCALER2_26     474
#define   ISCALER2_27     475
#define   ISCALER2_28     476
#define   ISCALER2_29     477
#define   ISCALER2_30     478
#define   ISCALER2_31     479

#define   ISCALER3_0     480
#define   ISCALER3_1     481
#define   ISCALER3_2     482
#define   ISCALER3_3     483
#define   ISCALER3_4     484
#define   ISCALER3_5     485
#define   ISCALER3_6     486
#define   ISCALER3_7     487
#define   ISCALER3_8     488
#define   ISCALER3_9     489
#define   ISCALER3_10     490
#define   ISCALER3_11     491
#define   ISCALER3_12     492
#define   ISCALER3_13     493
#define   ISCALER3_14     494
#define   ISCALER3_15     495
#define   ISCALER3_16     496
#define   ISCALER3_17     497
#define   ISCALER3_18     498
#define   ISCALER3_19     499
#define   ISCALER3_20     500
#define   ISCALER3_21     501
#define   ISCALER3_22     502
#define   ISCALER3_23     503
#define   ISCALER3_24     504
#define   ISCALER3_25     505
#define   ISCALER3_26     506
#define   ISCALER3_27     507
#define   ISCALER3_28     508
#define   ISCALER3_29     509
#define   ISCALER3_30     510
#define   ISCALER3_31     511


// Calibrated scalers

#define   SCCOFF     512     // Calibrated SCALERs start here

#define   ISCALER0_0_CAL     512
#define   ISCALER0_1_CAL     513
#define   ISCALER0_2_CAL     514
#define   ISCALER0_3_CAL     515
#define   ISCALER0_4_CAL     516
#define   ISCALER0_5_CAL     517
#define   ISCALER0_6_CAL     518
#define   ISCALER0_7_CAL     519
#define   ISCALER0_8_CAL     520
#define   ISCALER0_9_CAL     521
#define   ISCALER0_10_CAL     522
#define   ISCALER0_11_CAL     523
#define   ISCALER0_12_CAL     524
#define   ISCALER0_13_CAL     525
#define   ISCALER0_14_CAL     526
#define   ISCALER0_15_CAL     527
#define   ISCALER0_16_CAL     528
#define   ISCALER0_17_CAL     529
#define   ISCALER0_18_CAL     530
#define   ISCALER0_19_CAL     531
#define   ISCALER0_20_CAL     532
#define   ISCALER0_21_CAL     533
#define   ISCALER0_22_CAL     534
#define   ISCALER0_23_CAL     535
#define   ISCALER0_24_CAL     536
#define   ISCALER0_25_CAL     537
#define   ISCALER0_26_CAL     538
#define   ISCALER0_27_CAL     539
#define   ISCALER0_28_CAL     540
#define   ISCALER0_29_CAL     541
#define   ISCALER0_30_CAL     542
#define   ISCALER0_31_CAL     543

#define   ISCALER1_0_CAL     544
#define   ISCALER1_1_CAL     545
#define   ISCALER1_2_CAL     546
#define   ISCALER1_3_CAL     547
#define   ISCALER1_4_CAL     548
#define   ISCALER1_5_CAL     549
#define   ISCALER1_6_CAL     550
#define   ISCALER1_7_CAL     551
#define   ISCALER1_8_CAL     552
#define   ISCALER1_9_CAL     553
#define   ISCALER1_10_CAL     554
#define   ISCALER1_11_CAL     555
#define   ISCALER1_12_CAL     556
#define   ISCALER1_13_CAL     557
#define   ISCALER1_14_CAL     558
#define   ISCALER1_15_CAL     559
#define   ISCALER1_16_CAL     560
#define   ISCALER1_17_CAL     561
#define   ISCALER1_18_CAL     562
#define   ISCALER1_19_CAL     563
#define   ISCALER1_20_CAL     564
#define   ISCALER1_21_CAL     565
#define   ISCALER1_22_CAL     566
#define   ISCALER1_23_CAL     567
#define   ISCALER1_24_CAL     568
#define   ISCALER1_25_CAL     569
#define   ISCALER1_26_CAL     570
#define   ISCALER1_27_CAL     571
#define   ISCALER1_28_CAL     572
#define   ISCALER1_29_CAL     573
#define   ISCALER1_30_CAL     574
#define   ISCALER1_31_CAL     575

#define   ISCALER2_0_CAL     576
#define   ISCALER2_1_CAL     577
#define   ISCALER2_2_CAL     578
#define   ISCALER2_3_CAL     579
#define   ISCALER2_4_CAL     580
#define   ISCALER2_5_CAL     581
#define   ISCALER2_6_CAL     582
#define   ISCALER2_7_CAL     583
#define   ISCALER2_8_CAL     584
#define   ISCALER2_9_CAL     585
#define   ISCALER2_10_CAL     586
#define   ISCALER2_11_CAL     587
#define   ISCALER2_12_CAL     588
#define   ISCALER2_13_CAL     589
#define   ISCALER2_14_CAL     590
#define   ISCALER2_15_CAL     591
#define   ISCALER2_16_CAL     592
#define   ISCALER2_17_CAL     593
#define   ISCALER2_18_CAL     594
#define   ISCALER2_19_CAL     595
#define   ISCALER2_20_CAL     596
#define   ISCALER2_21_CAL     597
#define   ISCALER2_22_CAL     598
#define   ISCALER2_23_CAL     599
#define   ISCALER2_24_CAL     600
#define   ISCALER2_25_CAL     601
#define   ISCALER2_26_CAL     602
#define   ISCALER2_27_CAL     603
#define   ISCALER2_28_CAL     604
#define   ISCALER2_29_CAL     605
#define   ISCALER2_30_CAL     606
#define   ISCALER2_31_CAL     607

#define   ISCALER3_0_CAL     608
#define   ISCALER3_1_CAL     609
#define   ISCALER3_2_CAL     610
#define   ISCALER3_3_CAL     611
#define   ISCALER3_4_CAL     612
#define   ISCALER3_5_CAL     613
#define   ISCALER3_6_CAL     614
#define   ISCALER3_7_CAL     615
#define   ISCALER3_8_CAL     616
#define   ISCALER3_9_CAL     617
#define   ISCALER3_10_CAL     618
#define   ISCALER3_11_CAL     619
#define   ISCALER3_12_CAL     620
#define   ISCALER3_13_CAL     621
#define   ISCALER3_14_CAL     622
#define   ISCALER3_15_CAL     623
#define   ISCALER3_16_CAL     624
#define   ISCALER3_17_CAL     625
#define   ISCALER3_18_CAL     626
#define   ISCALER3_19_CAL     627
#define   ISCALER3_20_CAL     628
#define   ISCALER3_21_CAL     629
#define   ISCALER3_22_CAL     630
#define   ISCALER3_23_CAL     631
#define   ISCALER3_24_CAL     632
#define   ISCALER3_25_CAL     633
#define   ISCALER3_26_CAL     634
#define   ISCALER3_27_CAL     635
#define   ISCALER3_28_CAL     636
#define   ISCALER3_29_CAL     637
#define   ISCALER3_30_CAL     638
#define   ISCALER3_31_CAL     639


// TIR data from various crates

#define   TIROFF     640     // TIRs start here
#define   TIRNUM     4     // number of TIRs defined below

#define   ITIRDATA        640
#define   ITIRDATA1       641
#define   ITIRDATA2       642
#define   ITIRDATA3       643

// Helicity info from various crates

#define   HELOFF     644     // Helicities start here
#define   HELNUM     4     // number of HELs defined below

#define   IHELICITY        644
#define   IHELICITY1       645
#define   IHELICITY2       646
#define   IHELICITY3       647

// Timeslot info from various crates

#define   TIMOFF     648     // Timeslots start here
#define   TIMNUM     4     // number of timeslots defined below

#define   ITIMESLOT        648
#define   ITIMESLOT1       649
#define   ITIMESLOT2       650
#define   ITIMESLOT3       651

// Pairsynch info from various crates

#define   PAROFF     652     // Pairsynchs start here
#define   PARNUM     4     // number of pairsynchs defined below

#define   IPAIRSYNCH        652
#define   IPAIRSYNCH1       653
#define   IPAIRSYNCH2       654
#define   IPAIRSYNCH3       655

// Quadsynch info from various crates

#define   QUDOFF     656     // Quadsynchs start here
#define   QUDNUM     4     // number of quadsynchs defined below

#define   IQUADSYNCH        656
#define   IQUADSYNCH1       657
#define   IQUADSYNCH2       658
#define   IQUADSYNCH3       659

// Timeboard data from various crates

#define   TBDOFF     660     // Timeboards start here
#define   TBDNUM     4     // number of timeboards defined below

#define   ITIMEBOARD        660
#define   ITIMEBOARD1       661
#define   ITIMEBOARD2       662
#define   ITIMEBOARD3       663

#define   IRAMPDELAY        664
#define   IRAMPDELAY1       665
#define   IRAMPDELAY2       666
#define   IRAMPDELAY3       667

#define   IINTEGTIME        668
#define   IINTEGTIME1       669
#define   IINTEGTIME2       670
#define   IINTEGTIME3       671

#define   IOVERSAMPLE        672
#define   IOVERSAMPLE1       673
#define   IOVERSAMPLE2       674
#define   IOVERSAMPLE3       675

#define   IPRECDAC        676
#define   IPRECDAC1       677
#define   IPRECDAC2       678
#define   IPRECDAC3       679

#define   IPITADAC        680
#define   IPITADAC1       681
#define   IPITADAC2       682
#define   IPITADAC3       683

// Lumi detectors

#define   LMIOFF     684     // Lumis start here
#define   LMINUM     4     // number of lumis defined below

// R = raw data; "" = calibrated data

#define   ILUMI1R     684
#define   ILUMI1      685

#define   ILUMI2R     686
#define   ILUMI2      687

#define   ILUMI3R     688
#define   ILUMI3      689

#define   ILUMI4R     690
#define   ILUMI4      691


// V2f_Clocks

#define   V2FCLKOFF     692     // V2F clocks start here
#define   V2FCLKNUM     4     // number of V2F clocks defined below

#define   IV2F_CLK0      692
#define   IV2F_CLK1      693
#define   IV2F_CLK2      694
#define   IV2F_CLK3      695

// Quad photodiodes

#define   QPDOFF     696     // Quad photodiodes start here
#define   QPDNUM     1     // number of quad photodiodes defined below

// PP, PM, MP, MM = diodes (x side, y side); X, Y = calibrated position;
// SUM = X, Y, and total diode sum

// Quad photodiodes 
#define   IQPD1PP   696
#define   IQPD1PM   697
#define   IQPD1MP   698
#define   IQPD1MM   699
#define   IQPD1X    700
#define   IQPD1Y    701
#define   IQPD1SUM  702


// bmw words

#define   BMWOFF     703     // bmw words start here
#define   BMWNUM     4     // number of bmw words defined below

#define   IBMW_CLN      703
#define   IBMW_OBJ      704
#define   IBMW_VAL      705
#define   IBMW_CYC      706

